### ISSUE TITLE
!leavemessage accepts invalid nicknames

### ISSUE THREAD

**Issue by lucasdealmeidasm** [collingreen/yaib#14]
Accidentally discovered while making the common mistake of forgetting the nickname, see:

<drnick> !leavemessage isn't there a patent or something on using korobeiniki on games?
<yaib> Message saved for isn't

then further tested:

<drnick> !leavemessage éÈöüãñÔ Hi keeyai
<yaib> Message saved for éÈöüãñÔ

**Comment by collingreen** [comment]
What is a valid nickname? How would yaib know which is valid and which is not?

**Comment by collingreen** [comment]
Closing this - further discussion should be on the leavemessage plugin.

Also, perhaps this enhancement will help? https://github.com/collingreen/yaib_plugin_leavemessage/issues/1
